SELECT FLAVOR
FROM FIRST_HALF
WHERE TOTAL_ORDER > 3000
AND (
    SELECT INGREDIENT_TYPE
    FROM ICECREAM_INFO
    WHERE ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR) = 'fruit_based'
ORDER BY TOTAL_ORDER DESC
;